// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snapshot 是某一时刻的计数快照。
 */
export interface Snapshot {
    /**
     * 累计发送字节
     */
    "tx": number;

    /**
     * 累计接收字节
     */
    "rx": number;

    /**
     * 当前活跃连接数
     */
    "activeConn": number;

    /**
     * 累计连接数
     */
    "totalConn": number;
}
