// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostService 暴露主机 CRUD 与连通性测试。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../core/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除主机（引用它的隧道一并删除）。
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3808010823, id);
}

/**
 * ListHosts 返回全部主机。
 */
export function List(): $CancellablePromise<config$0.Host[] | null> {
    return $Call.ByID(3548704148);
}

/**
 * Save 创建或更新主机。
 */
export function Save(host: config$0.Host): $CancellablePromise<void> {
    return $Call.ByID(2520353641, host);
}

/**
 * TestConnection performs a bounded, one-shot SSH handshake for a saved host.
 * It follows the same ProxyJump/authentication/host-key path as tunnels, but
 * does not register a runtime tunnel and closes the client immediately after
 * a successful handshake.
 */
export function TestConnection(id: string): $CancellablePromise<$models.HostTestResult | null> {
    return $Call.ByID(1672373696, id);
}
