// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stats$0 from "../core/stats/models.js";

/**
 * AppInfo 返回应用信息（前端关于页/调试用）。
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "configPath": string;
}

/**
 * CreateTunnelRequest 是 New Tunnel 弹窗的提交载荷。
 */
export interface CreateTunnelRequest {
    "name": string;
    "hostId": string;

    /**
     * L | R | D
     */
    "type": string;
    "localBindHost"?: string;
    "localPort"?: number;
    "localSocket"?: string;
    "targetHost"?: string;
    "targetPort"?: number;
    "targetSocket"?: string;
    "remoteBindHost"?: string;
    "remotePort"?: number;
    "socksPort"?: number;
    "autoStart": boolean;
}

/**
 * TunnelView 是隧道配置 + 运行时状态的组合视图。
 */
export interface TunnelView {
    "id": string;
    "name": string;

    /**
     * 使用的 SSH 主机
     */
    "hostId": string;

    /**
     * L | R | D
     */
    "type": string;

    /**
     * -L：本地监听 → 经 SSH 到目标。
     * 默认 127.0.0.1
     */
    "localBindHost"?: string;
    "localPort"?: number;

    /**
     * 本地 unix socket（与 LocalPort 二选一）
     */
    "localSocket"?: string;

    /**
     * -L 目标主机
     */
    "targetHost"?: string;

    /**
     * -L 目标端口
     */
    "targetPort"?: number;

    /**
     * 服务器侧 unix socket（与 TargetHost/Port 二选一）
     */
    "targetSocket"?: string;

    /**
     * -R：服务器侧监听 → 经 SSH 回本地目标。
     */
    "remoteBindHost"?: string;
    "remotePort"?: number;
    "remoteSocket"?: string;

    /**
     * -D：SOCKS 监听端口。
     */
    "socksPort"?: number;
    "autoStart": boolean;
    "status": string;
    "running": boolean;
    "error": string;
    "stats": stats$0.Snapshot;
}

/**
 * UpdateTunnelRequest 是编辑隧道的提交载荷。
 */
export interface UpdateTunnelRequest {
    "id": string;
    "name": string;
    "hostId": string;

    /**
     * L | R | D
     */
    "type": string;
    "localBindHost"?: string;
    "localPort"?: number;
    "localSocket"?: string;
    "targetHost"?: string;
    "targetPort"?: number;
    "targetSocket"?: string;
    "remoteBindHost"?: string;
    "remotePort"?: number;
    "socksPort"?: number;
    "autoStart": boolean;
}
