// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunnelService 暴露隧道 CRUD 与启停。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create 创建隧道并持久化。
 */
export function Create(req: $models.CreateTunnelRequest): $CancellablePromise<$models.TunnelView | null> {
    return $Call.ByID(2799198192, req);
}

/**
 * CreateFromSSHCommand 解析 `ssh -L ... user@host` 并创建主机 + 隧道。
 * 返回新建的隧道视图列表。
 */
export function CreateFromSSHCommand(cmd: string): $CancellablePromise<$models.TunnelView[] | null> {
    return $Call.ByID(1197033139, cmd);
}

/**
 * Delete 删除隧道（运行中会先停止）。
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(409837647, id);
}

/**
 * Get 按 ID 返回单个隧道视图。
 */
export function Get(id: string): $CancellablePromise<$models.TunnelView | null> {
    return $Call.ByID(2931146336, id);
}

/**
 * List 返回全部隧道及其实时状态。
 */
export function List(): $CancellablePromise<$models.TunnelView[] | null> {
    return $Call.ByID(3075803916);
}

/**
 * Start 启动隧道。
 */
export function Start(id: string): $CancellablePromise<void> {
    return $Call.ByID(2120183912, id);
}

/**
 * Stop 停止隧道。
 */
export function Stop(id: string): $CancellablePromise<void> {
    return $Call.ByID(3810308172, id);
}

/**
 * Update 更新已有隧道配置（运行中会先停止并在保存后重新启动）。
 */
export function Update(req: $models.UpdateTunnelRequest): $CancellablePromise<$models.TunnelView | null> {
    return $Call.ByID(3447997413, req);
}
