// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthConfig 认证配置。
 */
export interface AuthConfig {
    /**
     * password | key | agent
     */
    "method": string;
    "password"?: string;
    "keyPath"?: string;
    "keyPassphrase"?: string;
    "agentSocket"?: string;
}

/**
 * Host 是一台 SSH 服务器（含认证与跳板配置）。
 */
export interface Host {
    "id": string;
    "name": string;
    "host": string;
    "port": number;
    "user": string;
    "auth": AuthConfig;

    /**
     * JumpHostIDs 为跳板链，按从近到远排列。
     */
    "jumpHostIds"?: string[] | null;

    /**
     * 0 = 默认 15s
     */
    "keepaliveSeconds"?: number;
    "knownHostsFile"?: string;
}
